{"hierarchy":{"paths":[["doc:\/\/SwiftDirector\/documentation\/SwiftDirector"]]},"identifier":{"url":"doc:\/\/SwiftDirector\/documentation\/SwiftDirector\/LDAPError","interfaceLanguage":"swift"},"kind":"symbol","schemaVersion":{"major":0,"patch":0,"minor":2},"topicSections":[{"identifiers":["doc:\/\/SwiftDirector\/documentation\/SwiftDirector\/LDAPError\/description"],"title":"Instance Properties"},{"identifiers":["doc:\/\/SwiftDirector\/documentation\/SwiftDirector\/LDAPError\/unknown"],"title":"Type Properties"},{"generated":true,"identifiers":["doc:\/\/SwiftDirector\/documentation\/SwiftDirector\/LDAPError\/Equatable-Implementations"],"title":"Default Implementations"}],"abstract":[{"text":"The error type representing errors occurring during LDAP operations.","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/swiftdirector\/ldaperror"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"LDAPError","kind":"identifier"}],"platforms":["Linux"]}]}],"relationshipsSections":[{"type":"conformsTo","kind":"relationships","identifiers":["doc:\/\/SwiftDirector\/s23CustomStringConvertibleP","doc:\/\/SwiftDirector\/SQ","doc:\/\/SwiftDirector\/s5ErrorP","doc:\/\/SwiftDirector\/s8SendableP"],"title":"Conforms To"}],"metadata":{"roleHeading":"Structure","title":"LDAPError","externalID":"s:13SwiftDirector9LDAPErrorV","modules":[{"name":"SwiftDirector"}],"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"LDAPError"}],"symbolKind":"struct","navigatorTitle":[{"kind":"identifier","text":"LDAPError"}],"role":"symbol"},"sections":[],"references":{"doc://SwiftDirector/s23CustomStringConvertibleP":{"identifier":"doc:\/\/SwiftDirector\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible","type":"unresolvable"},"doc://SwiftDirector/documentation/SwiftDirector":{"kind":"symbol","title":"SwiftDirector","abstract":[],"type":"topic","identifier":"doc:\/\/SwiftDirector\/documentation\/SwiftDirector","url":"\/documentation\/swiftdirector","role":"collection"},"doc://SwiftDirector/s5ErrorP":{"identifier":"doc:\/\/SwiftDirector\/s5ErrorP","title":"Swift.Error","type":"unresolvable"},"doc://SwiftDirector/documentation/SwiftDirector/LDAPError/Equatable-Implementations":{"identifier":"doc:\/\/SwiftDirector\/documentation\/SwiftDirector\/LDAPError\/Equatable-Implementations","kind":"article","type":"topic","role":"collectionGroup","title":"Equatable Implementations","abstract":[],"url":"\/documentation\/swiftdirector\/ldaperror\/equatable-implementations"},"doc://SwiftDirector/SQ":{"identifier":"doc:\/\/SwiftDirector\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://SwiftDirector/documentation/SwiftDirector/LDAPError":{"type":"topic","url":"\/documentation\/swiftdirector\/ldaperror","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"LDAPError"}],"identifier":"doc:\/\/SwiftDirector\/documentation\/SwiftDirector\/LDAPError","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"LDAPError"}],"title":"LDAPError","abstract":[{"type":"text","text":"The error type representing errors occurring during LDAP operations."}]},"doc://SwiftDirector/documentation/SwiftDirector/LDAPError/description":{"role":"symbol","type":"topic","title":"description","url":"\/documentation\/swiftdirector\/ldaperror\/description","kind":"symbol","abstract":[],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"description"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"identifier":"doc:\/\/SwiftDirector\/documentation\/SwiftDirector\/LDAPError\/description"},"doc://SwiftDirector/documentation/SwiftDirector/LDAPError/unknown":{"identifier":"doc:\/\/SwiftDirector\/documentation\/SwiftDirector\/LDAPError\/unknown","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"An unknown error that does not correspond to any LDAP error."},{"text":" ","type":"text"},{"text":"Usually occurs if ldap returned a success status code but not the necessary results.","type":"text"}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"unknown"},{"kind":"text","text":": "},{"preciseIdentifier":"s:13SwiftDirector9LDAPErrorV","kind":"typeIdentifier","text":"LDAPError"}],"title":"unknown","url":"\/documentation\/swiftdirector\/ldaperror\/unknown","role":"symbol"},"doc://SwiftDirector/s8SendableP":{"identifier":"doc:\/\/SwiftDirector\/s8SendableP","title":"Swift.Sendable","type":"unresolvable"}}}